name = "AnalysisOfVariance"
uuid = "01c9c671-d471-43d2-8b89-3af15e6b824d"
version = "v0.1.4"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SweepOperator = "7522ee7d-7047-56d0-94d9-4bc626e7058d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"

[compat]
julia = "1.6"
CategoricalArrays = "0.1"
SweepOperator = "0.3.4"
DataFrames = "1.7"
GLM = "1.0"
StatsModels = "0.5"
PrettyTables = "2.0"
Printf = "0.5"
Distributions = "0.25"
